# Makefile autogenerated by Dyi on October 23, 2017
#
# Main target: all
# Sources:  src/expandContent.js  src/index.js  src/messages.js  src/pack.js  src/parse.js  src/readVerticals.js  src/test.js 

.DEFAULT_GOAL := all


.PHONY: docs
docs: k-8qyhc46a k-2n5ob7xw k-h70nowek k-frmquaq7 k-c7ugypfv


.PHONY: c-lou4qo1c
c-lou4qo1c: lib/expandContent.js lib/index.js lib/messages.js lib/pack.js lib/parse.js lib/readVerticals.js lib/test.js


.PHONY: build
build: c-lou4qo1c


.PHONY: test
test: k-tsl5hans k-98yfoj56


.PHONY: sandbox
sandbox: k-91gbe66d


.PHONY: update
update: k-sceadbxq


.PHONY: major
major: k-wpnkkeiw k-ka3b4r16 k-e625nw8g


.PHONY: minor
minor: k-s2oimfq9 k-jbgyf72m k-sr9d1bkj


.PHONY: patch
patch: k-6272lago k-bigwo4ui k-jxaj0nh4


.PHONY: prepare
prepare: lib




.PHONY: k-8qyhc46a
k-8qyhc46a:  
	./node_modules/.bin/mustache package.json docs/readme.md | ./node_modules/.bin/stupid-replace '~USAGE~' -f docs/usage.md > readme.md


.PHONY: k-2n5ob7xw
k-2n5ob7xw:  
	cat history.md >> readme.md


.PHONY: k-h70nowek
k-h70nowek:  
	mkdir -p ./man/man1


.PHONY: k-frmquaq7
k-frmquaq7:  
	pandoc -s -f markdown -t man readme.md > ./man/man1/gitbook3toedx.1


.PHONY: k-c7ugypfv
k-c7ugypfv:  
	-hub cm 'update docs and history.md'


.PHONY: k-u2mmqbai
k-u2mmqbai:  
	((echo '#!/usr/bin/env node') && cat ./lib/index.js) > index.js


.PHONY: k-mmc1cs4w
k-mmc1cs4w:  
	chmod +x ./index.js


.PHONY: all
all: 
	make build 
	make k-u2mmqbai 
	make k-mmc1cs4w  


.PHONY: k-tsl5hans
k-tsl5hans:  
	make all


.PHONY: k-98yfoj56
k-98yfoj56:  
	./node_modules/.bin/mocha lib/test.js


.PHONY: k-91gbe66d
k-91gbe66d:  
	./node_modules/.bin/babel-node src/sandbox.js


.PHONY: k-sceadbxq
k-sceadbxq:  
	make clean && ./node_modules/.bin/babel configure.js | node


.PHONY: k-wpnkkeiw
k-wpnkkeiw:  
	make all


.PHONY: k-ka3b4r16
k-ka3b4r16:  
	make docs


.PHONY: k-e625nw8g
k-e625nw8g:  
	./node_modules/.bin/xyz -i major


.PHONY: k-s2oimfq9
k-s2oimfq9:  
	make all


.PHONY: k-jbgyf72m
k-jbgyf72m:  
	make docs


.PHONY: k-sr9d1bkj
k-sr9d1bkj:  
	./node_modules/.bin/xyz -i minor


.PHONY: k-6272lago
k-6272lago:  
	make all


.PHONY: k-bigwo4ui
k-bigwo4ui:  
	make docs


.PHONY: k-jxaj0nh4
k-jxaj0nh4:  
	./node_modules/.bin/xyz -i patch


.PHONY: clean
clean:  
	rm -f lib/expandContent.js
	rm -f lib/index.js
	rm -f lib/messages.js
	rm -f lib/pack.js
	rm -f lib/parse.js
	rm -f lib/readVerticals.js
	rm -f lib/test.js




lib/expandContent.js: src/expandContent.js 
	./node_modules/.bin/babel src/expandContent.js -o ./lib/expandContent.js

lib/index.js: src/index.js 
	./node_modules/.bin/babel src/index.js -o ./lib/index.js

lib/messages.js: src/messages.js 
	./node_modules/.bin/babel src/messages.js -o ./lib/messages.js

lib/pack.js: src/pack.js 
	./node_modules/.bin/babel src/pack.js -o ./lib/pack.js

lib/parse.js: src/parse.js 
	./node_modules/.bin/babel src/parse.js -o ./lib/parse.js

lib/readVerticals.js: src/readVerticals.js 
	./node_modules/.bin/babel src/readVerticals.js -o ./lib/readVerticals.js

lib/test.js: src/test.js 
	./node_modules/.bin/babel src/test.js -o ./lib/test.js

lib: 
	mkdir -p lib

