# Makefile autogenerated by Dyi on March 29, 2016
#
# Main target: all
# Sources:  src/expandContent.js  src/index.js  src/messages.js  src/pack.js  src/parse.js  src/readVerticals.js  src/test.js 

.DEFAULT_GOAL := all


.PHONY: docs
docs: k-hxh845jq k-ypjj5f37 k-2194p6j3 k-5cnfkqnx k-e9fot859 k-ws43f9id


.PHONY: c-14lnqko7
c-14lnqko7: lib/expandContent.js lib/index.js lib/messages.js lib/pack.js lib/parse.js lib/readVerticals.js lib/test.js


.PHONY: build
build: c-14lnqko7


.PHONY: test
test: k-rkte15ns k-8nhwhgfi


.PHONY: sandbox
sandbox: k-gvbwxmv4


.PHONY: update
update: k-ww3ctm1d


.PHONY: major
major: k-fhcldwwv k-bqyjadub k-e1f3r915


.PHONY: minor
minor: k-d1q0y5cw k-61jc1rea k-jd1gyhvs


.PHONY: patch
patch: k-3n3pm3il k-wodc7e30 k-g5rtc9tx


.PHONY: prepare
prepare: lib




.PHONY: k-hxh845jq
k-hxh845jq:  
	./node_modules/.bin/git-hist history.md


.PHONY: k-ypjj5f37
k-ypjj5f37:  
	./node_modules/.bin/mustache package.json docs/readme.md | ./node_modules/.bin/stupid-replace '~USAGE~' -f docs/usage.md > readme.md


.PHONY: k-2194p6j3
k-2194p6j3:  
	cat history.md >> readme.md


.PHONY: k-5cnfkqnx
k-5cnfkqnx:  
	mkdir -p ./man/man1


.PHONY: k-e9fot859
k-e9fot859:  
	pandoc -s -f markdown -t man readme.md > ./man/man1/gitbook3toedx.1


.PHONY: k-ws43f9id
k-ws43f9id:  
	-hub cm 'update docs and history.md'


.PHONY: k-343oqfml
k-343oqfml:  
	((echo '#!/usr/bin/env node') && cat ./lib/index.js) > index.js


.PHONY: k-hm7rcmur
k-hm7rcmur:  
	chmod +x ./index.js


.PHONY: all
all: 
	make build 
	make k-343oqfml 
	make k-hm7rcmur  


.PHONY: k-rkte15ns
k-rkte15ns:  
	make all


.PHONY: k-8nhwhgfi
k-8nhwhgfi:  
	./node_modules/.bin/mocha lib/test.js


.PHONY: k-gvbwxmv4
k-gvbwxmv4:  
	./node_modules/.bin/babel-node src/sandbox.js


.PHONY: k-ww3ctm1d
k-ww3ctm1d:  
	make clean && ./node_modules/.bin/babel configure.js | node


.PHONY: k-fhcldwwv
k-fhcldwwv:  
	make all


.PHONY: k-bqyjadub
k-bqyjadub:  
	make docs


.PHONY: k-e1f3r915
k-e1f3r915:  
	./node_modules/.bin/xyz -i major


.PHONY: k-d1q0y5cw
k-d1q0y5cw:  
	make all


.PHONY: k-61jc1rea
k-61jc1rea:  
	make docs


.PHONY: k-jd1gyhvs
k-jd1gyhvs:  
	./node_modules/.bin/xyz -i minor


.PHONY: k-3n3pm3il
k-3n3pm3il:  
	make all


.PHONY: k-wodc7e30
k-wodc7e30:  
	make docs


.PHONY: k-g5rtc9tx
k-g5rtc9tx:  
	./node_modules/.bin/xyz -i patch


.PHONY: clean
clean:  
	rm -f lib/expandContent.js
	rm -f lib/index.js
	rm -f lib/messages.js
	rm -f lib/pack.js
	rm -f lib/parse.js
	rm -f lib/readVerticals.js
	rm -f lib/test.js




lib/expandContent.js: src/expandContent.js 
	./node_modules/.bin/babel src/expandContent.js -o ./lib/expandContent.js

lib/index.js: src/index.js 
	./node_modules/.bin/babel src/index.js -o ./lib/index.js

lib/messages.js: src/messages.js 
	./node_modules/.bin/babel src/messages.js -o ./lib/messages.js

lib/pack.js: src/pack.js 
	./node_modules/.bin/babel src/pack.js -o ./lib/pack.js

lib/parse.js: src/parse.js 
	./node_modules/.bin/babel src/parse.js -o ./lib/parse.js

lib/readVerticals.js: src/readVerticals.js 
	./node_modules/.bin/babel src/readVerticals.js -o ./lib/readVerticals.js

lib/test.js: src/test.js 
	./node_modules/.bin/babel src/test.js -o ./lib/test.js

lib: 
	mkdir -p lib

