# Makefile autogenerated by Dyi on October 16, 2017
#
# Main target: all
# Sources:  src/expandContent.js  src/index.js  src/messages.js  src/pack.js  src/parse.js  src/readVerticals.js  src/test.js 

.DEFAULT_GOAL := all


.PHONY: docs
docs: k-ii1l9sbl k-irfd7v9i k-ja4480ut k-yufut119 k-xg8tgwhl k-pnuukntr


.PHONY: c-kdjsyy86
c-kdjsyy86: lib/expandContent.js lib/index.js lib/messages.js lib/pack.js lib/parse.js lib/readVerticals.js lib/test.js


.PHONY: build
build: c-kdjsyy86


.PHONY: test
test: k-cf5m4ns5 k-r36njhb3


.PHONY: sandbox
sandbox: k-8a211kfe


.PHONY: update
update: k-xqq79b0k


.PHONY: major
major: k-deb1br7f k-oyiqaf0n k-6rh57jwn


.PHONY: minor
minor: k-sm0s6m7l k-w09rs1n4 k-xeg54ho5


.PHONY: patch
patch: k-iuupgdni k-76eaaftv k-ro30kkbq


.PHONY: prepare
prepare: lib




.PHONY: k-ii1l9sbl
k-ii1l9sbl:  
	./node_modules/.bin/git-hist history.md


.PHONY: k-irfd7v9i
k-irfd7v9i:  
	./node_modules/.bin/mustache package.json docs/readme.md | ./node_modules/.bin/stupid-replace '~USAGE~' -f docs/usage.md > readme.md


.PHONY: k-ja4480ut
k-ja4480ut:  
	cat history.md >> readme.md


.PHONY: k-yufut119
k-yufut119:  
	mkdir -p ./man/man1


.PHONY: k-xg8tgwhl
k-xg8tgwhl:  
	pandoc -s -f markdown -t man readme.md > ./man/man1/gitbook3toedx.1


.PHONY: k-pnuukntr
k-pnuukntr:  
	-hub cm 'update docs and history.md'


.PHONY: k-g5g1114h
k-g5g1114h:  
	((echo '#!/usr/bin/env node') && cat ./lib/index.js) > index.js


.PHONY: k-l4hj4xut
k-l4hj4xut:  
	chmod +x ./index.js


.PHONY: all
all: 
	make build 
	make k-g5g1114h 
	make k-l4hj4xut  


.PHONY: k-cf5m4ns5
k-cf5m4ns5:  
	make all


.PHONY: k-r36njhb3
k-r36njhb3:  
	./node_modules/.bin/mocha lib/test.js


.PHONY: k-8a211kfe
k-8a211kfe:  
	./node_modules/.bin/babel-node src/sandbox.js


.PHONY: k-xqq79b0k
k-xqq79b0k:  
	make clean && ./node_modules/.bin/babel configure.js | node


.PHONY: k-deb1br7f
k-deb1br7f:  
	make all


.PHONY: k-oyiqaf0n
k-oyiqaf0n:  
	make docs


.PHONY: k-6rh57jwn
k-6rh57jwn:  
	./node_modules/.bin/xyz -i major


.PHONY: k-sm0s6m7l
k-sm0s6m7l:  
	make all


.PHONY: k-w09rs1n4
k-w09rs1n4:  
	make docs


.PHONY: k-xeg54ho5
k-xeg54ho5:  
	./node_modules/.bin/xyz -i minor


.PHONY: k-iuupgdni
k-iuupgdni:  
	make all


.PHONY: k-76eaaftv
k-76eaaftv:  
	make docs


.PHONY: k-ro30kkbq
k-ro30kkbq:  
	./node_modules/.bin/xyz -i patch


.PHONY: clean
clean:  
	rm -f lib/expandContent.js
	rm -f lib/index.js
	rm -f lib/messages.js
	rm -f lib/pack.js
	rm -f lib/parse.js
	rm -f lib/readVerticals.js
	rm -f lib/test.js




lib/expandContent.js: src/expandContent.js 
	./node_modules/.bin/babel src/expandContent.js -o ./lib/expandContent.js

lib/index.js: src/index.js 
	./node_modules/.bin/babel src/index.js -o ./lib/index.js

lib/messages.js: src/messages.js 
	./node_modules/.bin/babel src/messages.js -o ./lib/messages.js

lib/pack.js: src/pack.js 
	./node_modules/.bin/babel src/pack.js -o ./lib/pack.js

lib/parse.js: src/parse.js 
	./node_modules/.bin/babel src/parse.js -o ./lib/parse.js

lib/readVerticals.js: src/readVerticals.js 
	./node_modules/.bin/babel src/readVerticals.js -o ./lib/readVerticals.js

lib/test.js: src/test.js 
	./node_modules/.bin/babel src/test.js -o ./lib/test.js

lib: 
	mkdir -p lib

